@startuml Prototype
class Manager {
    -showcase

    +register()
    +create()
}

interface Product {
    {abstract} +use()
    {abstract} +createClone()
}

class UnderlinePen implements Product {
    -uichar

    +use()
    +createClone()
}

class MessageBox implements Product {
    -decochar
    
    +use()
    +createClone()
}

Manager --> Product : Uses >
@enduml