@startuml adaptor
class Main {

}

interface Print {
    {abstract} +printWeak()
    {abstract} +printStrong()
}

class PrintBanner extends Banner implements Print {
    +printWeak()
    +printStrong()
}

class Banner {
    +showWithParen()
    +showWithAster()
}

Main --> Print : Uses >
@enduml